### ISSUE TITLE
xtraceback v0.3: function return types differ after monkey patching

### ISSUE THREAD

**Issue by sniffer** [0compute/xtraceback#1]
For example format_exc() returns a list instead of a string.

This should expain all:

```
>>> import traceback
>>> try:
...     raise Exception("asdasd")
... except:
...     traceback.format_exc()
...
'Traceback (most recent call last):\n  File "<stdin>", line 2, in <module>\nException: asdasd\n'
>>> try:
...     raise Exception("asdasd")
... except:
...     traceback.format_exc().splitlines()
...
['Traceback (most recent call last):', '  File "<stdin>", line 2, in <module>', 'Exception: asdasd']
>>> 
>>> 
>>> import xtraceback
>>> xtraceback.compat.install()
>>> try:
...     raise Exception("asdasd")
... except:
...     traceback.format_exc()
... 
['Traceback (most recent call last):\n', '  File "<stdin>", line 2, in <module>\n    g:traceback = <module \'traceback\' from=\'/usr/lib64/python2.6/traceback.pyc\'>\n    g:xtraceback = <package \'xtraceback\' from=\'../../pyenv/lib/python2.6/site-packages/xtraceback-0.3-py2.6.egg/xtraceback\'>\n', 'Exception: asdasd\n']
```

**Comment by sniffer** [comment]
`xtraceback.py`

```
    def _str_lines(self, lines):
        exc_str = "".join(lines)
        if self.color:
            exc_str = self._highlight(exc_str)
        return exc_str

    def _format_lines(self, lines):
        return map(self._highlight, lines) if self.color else lines

    def _print_lines(self, lines):
        if self.options.stream is None:
            raise RuntimeError("Cannot print - %r has None stream" % self)
        self.options.stream.write(self._str_lines(lines))

    # { Traceback format - these return lines that should be joined with ""

    def _format_tb(self):
        return [ "%s\n" % frame for frame in self.tb_frames ]
```

`stdlibcompat.py`

```
    def format_exc(self, limit=None, **options):
        return "".join(self.format_exception(*sys.exc_info(), limit=limit, **options))
```

Some code cleanup and bugfix for format_exception()

**Comment by kingarrrt** [comment]
Done. Thanks.
